apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: googletest1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: googletest1
    spec:
      containers:
      - name: googletest1
        image: deepshikharai/demodockerc:latest
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: selenium-hub
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
